######################## default configuration ####################
baseURL: /
title: Corporate Software AG – Cloud-IT-Lösungen für Unternehmen
description: CoSo begeistert als Schweizer Unternehmen seit 2011 Kund:innen mit nachhaltigen Lösungskonzepten an der Schnittstelle zwischen Business und IT. Wir arbeiten in und mit der Microsoft Cloud.
theme: hugo-theme-copper
author: Thomas
googleAnalytics: UA-127897200-1
contact_form_action: '#'
appinsights_instrumentationkey: f6f701e5-fd55-4628-9671-2d421f641d74
paginate: 6
summaryLength: 10
defaultContentLanguage: de
disableLanguages:
  - fr
  - en # desable language from here
outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    renderer:
      unsafe: true