de:
  languageName: De
  languageCode: ch-de
  contentDir: content/german
  params:
    weight: 1
    footer_content: Footer Test Text in Deutsch
    title_404: Nicht gefunden
    text_404: Wir konnten die angefragte Seite nicht finden.
    button_404: Zurück zu Home
    copyright: Corporate Software AG

en:
  languageName: En
  languageCode: en-en
  contentDir: content/english
  params:
    weight: 2
    footer_content: Footer test text in English
    title_404: Not Found
    text_404: Not abel to find this site...
    button_404: back to home
    copyright: Corporate Software AG